In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os
import matplotlib.pyplot as plt
import matplotlib
matplotlib.style.use('ggplot')
from __future__ import unicode_literals

In [10]:
# general visualisation
library('ggplot2') # visualisation
library('scales') # visualisation
library('grid') # visualisation
library('gridExtra') # visualisation
library('RColorBrewer') # visualisation
library('corrplot') # visualisation

# general data manipulation
library('dplyr') # data manipulation
library('readr') # input/output
library('data.table') # data manipulation
library('tibble') # data wrangling
library('tidyr') # data wrangling
library('stringr') # string manipulation
library('forcats') # factor manipulation

# specific visualisation
library('ggrepel') # visualisation
library('treemapify') # visualisation
library('ggforce') # visualisation
library('ggridges') # visualization

# specific data manipulation
library('broom') # data wrangling
library('purrr') # string manipulation

# Date plus forecast
library('lubridate') # date and time
library('timeDate') # date and time

NameError: name 'library' is not defined

In [11]:
train = pd.read_csv('C:/Users/AnupamaRatha/Desktop/Albertsons/data/sampledata/transactions.csv', encoding='utf-8')

train.head()

,Calander day,upc_id,upc_dsc,category_id,category_nm,group_id,group_nm,department_id,department_nm,total_net_sales,...,items_per_week_per_store,baskets_per_week_per_store,total_net_sales_per_day_per_store,items_per_day_per_store,baskets_per_day_per_store,N,item_rank,item_rank_ntile,daily_ind,period
0,1/1/2018,48406000701,BANANAS YELLOW REGULAR,8406,BANANAS,84,FRESH PRODUCE,329,PRODUCE,1.352734e+07,...,1867.2684,1813.4920,428.2971,266.7526,259.0703,88023,1,1,1,q1
1,1/2/2018,48404007501,AVOCADOS HASS LARGE,8404,AVOCADOS,84,FRESH PRODUCE,329,PRODUCE,1.416887e+07,...,2019.0990,871.1078,445.4627,288.4499,124.4502,88023,2,1,1,q1
2,1/3/2018,48106019201,HOT BAR BY THE LB LARGE SS,8106,SELF SERVICE PREPARED FOODS,81,FOOD SERVICE,306,FOOD SERVICE,5.722101e+04,...,534.4375,497.4375,510.9019,76.3482,71.0625,88023,3,1,1,q1
3,1/4/2018,48180065301,TIC TOK WOK BY THE LB HOT,8180,BAMBOO BAY ASIAN CUISINE,81,FOOD SERVICE,306,FOOD SERVICE,8.616977e+05,...,466.2633,427.0175,515.8280,67.0200,61.5105,88023,4,1,1,q1
4,1/5/2018,49515009501,BULK DONUT,9515,ISB BREAKFAST BAKED GOODS,95,IN-STORE SWEET BAKED GOODS,316,BAKERY,2.854840e+06,...,905.0713,417.0049,91.7921,129.4423,59.6413,88023,5,1,1,q1

In [18]:
data = train.groupby(['upc_id',"Calanderday"])
mean = data[["total_net_sales"]].mean()
mean = mean.add_suffix('').reset_index()
g = sns.relplot(y="total_net_sales", x="Calander date", data=mean, kind="line", hue="upc_id")

KeyError: 'Calanderday'

In [14]:
rm(list=ls())
suppressMessages(library(data.table))
suppressMessages(library(DT))
suppressMessages(library(timeSeries))
suppressMessages(library(tidyverse))
suppressMessages(library(reshape))
suppressMessages(library(stringr))
suppressMessages(library(doBy))
suppressMessages(library(formattable))
suppressMessages(library(gridExtra))

suppressMessages(library(ggplot2))
suppressMessages(library(plotly))
suppressMessages(library(corrplot))
suppressMessages(library(wesanderson))
suppressMessages(library(RColorBrewer))
suppressMessages(library(gridExtra))
suppressMessages(library(zoo))

suppressMessages(library(forecast))
suppressMessages(library(prophet)) ### For Prophet Forecasting
suppressMessages(library(nnfor))    ### For Neural Network Forecasting

NameError: name 'rm' is not defined